### ISSUE TITLE
Seems like osc/osc_global.h is missing

### ISSUE THREAD

**Issue by themolecule** [MugenSAS/osc-cpp-qt#1]
osc/osc_global.h is referred to in the .pro file, but not referenced by any of the source files.

Is this a missing file, or an extra line in the .pro file?

thanks!

**Comment by druidPollux** [comment]
Hello,
Sorry, this repo is a mirror of our internal repository and has not been updated since a while...

In fact the osc_global.h file is missing.
Originally it was used for symbol export. It has been replaced by OSC_API.h
I just update the repository to mirror our internal changes.

**Comment by themolecule** [comment]
thanks!

This library will really help me, and totally willing to contribute back... my other posted issue describes where I thought my starting place would be.  We can chat privately if you want.

**Comment by themolecule** [comment]
If you updated the repo... should I re-pull?

**Comment by druidPollux** [comment]
Yes, you can update your repo !
You can also send email to me directly using the github@mugen-sas.com email address.
